name: arch

description: MVVM architecture components for Flutter.

homepage: https://www.github.com/cross-solutions/arch

repository: https://www.github.com/cross-solutions/arch

issue_tracker: https://www.github.com/cross-solutions/arch/issues

documentation: https://pub.dev/documentation/arch/latest/

version: 0.0.1+2

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.1.8
  get_it: ^4.0.1
  provider: ^4.0.4
  page_transition: ^1.1.5

dev_dependencies:
  pedantic: ^1.8.0
