name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: [macos-latest]
    
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Publish to Pub Dev'
      uses: k-paxian/dart-package-publisher@v1.2
      with:
        accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
        refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
        dryRunOnly: true
        skipTests: true
